include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Ignorando temporariamente para o CI passar em projetos legados
    use_build_context_synchronously: ignore
    avoid_unnecessary_containers: ignore

linter:
  rules:
    avoid_print: false 
    use_key_in_widget_constructors: false
    library_private_types_in_public_api: false