const { initializeFirebase, admin } = require('./firebase-init');
const { applyTranslations } = require('./translations');

// Inicializar Firebase (aceita caminho do service account como argumento)
try {
  initializeFirebase(process.argv[2]);
} catch (error) {
  process.exit(1);
}

const db = admin.firestore();

// ═══════════════════════════════════════════════════════════════════════════
// DEFINIÇÃO DOS FORMULÁRIOS GLOBAIS POR SEGMENTO
// Path: /segments/{segmentId}/forms/{formId}
// ═══════════════════════════════════════════════════════════════════════════

const GLOBAL_FORMS = {
  // ═══════════════════════════════════════════════════════════
  // AUTOMOTIVO - Oficina Mecânica
  // ═══════════════════════════════════════════════════════════
  automotive: [
    {
      id: 'checklist_entrada_auto',
      title: 'Entrada do Veículo',
      description: 'Registre fotos e o estado inicial do veículo ao receber.',
      subspecialties: ['mechanical', 'carwash', 'painting', 'bodywork'],
      isActive: true,
      items: [
        {
          id: 'lataria_fotos',
          label: 'Fotos da Lataria (Avarias)',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'nivel_combustivel',
          label: 'Nível de Combustível',
          type: 'select',
          options: ['Reserva', '1/4', '1/2', '3/4', 'Cheio'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'luzes_painel',
          label: 'Luzes no Painel Acesas',
          type: 'checklist',
          options: ['Injeção', 'Freio ABS', 'Airbag', 'Bateria', 'Óleo', 'Motor', 'Temperatura'],
          required: false,
          allowPhotos: true,
        },
        {
          id: 'km_atual',
          label: 'Quilometragem Atual',
          type: 'number',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'pertences',
          label: 'Pertences no Veículo',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'revisao_basica',
      title: 'Revisão Básica',
      description: 'Confirma troca de óleo, filtros e níveis de fluidos.',
      subspecialties: ['mechanical'],
      isActive: true,
      items: [
        {
          id: 'oleo_motor',
          label: 'Óleo do Motor Trocado',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'filtro_oleo',
          label: 'Filtro de Óleo Trocado',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'filtro_ar',
          label: 'Filtro de Ar Verificado',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'filtro_cabine',
          label: 'Filtro de Cabine Verificado',
          type: 'boolean',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'nivel_liquidos',
          label: 'Verificação dos Níveis',
          type: 'checklist',
          options: ['Arrefecimento', 'Freio', 'Direção Hidráulica', 'Limpador'],
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'inspecao_freios',
      title: 'Inspeção de Freios',
      description: 'Avalie pastilhas, discos e fluido para indicar trocas.',
      subspecialties: ['mechanical'],
      isActive: true,
      items: [
        {
          id: 'pastilhas_dianteiras',
          label: 'Estado das Pastilhas Dianteiras',
          type: 'select',
          options: ['Bom (>50%)', 'Regular (30-50%)', 'Desgastado (<30%)', 'Trocar'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'pastilhas_traseiras',
          label: 'Estado das Pastilhas Traseiras',
          type: 'select',
          options: ['Bom (>50%)', 'Regular (30-50%)', 'Desgastado (<30%)', 'Trocar'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'discos_dianteiros',
          label: 'Discos Dianteiros',
          type: 'select',
          options: ['OK', 'Empenado', 'Desgastado', 'Trocar'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'fluido_freio',
          label: 'Fluido de Freio',
          type: 'select',
          options: ['OK', 'Baixo', 'Contaminado', 'Trocar'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'freio_mao',
          label: 'Freio de Mão Funcionando',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'observacoes_freios',
          label: 'Observações',
          type: 'text',
          required: false,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'teste_rodagem',
      title: 'Teste de Rodagem',
      description: 'Valide o veículo após o serviço em curto trajeto.',
      subspecialties: ['mechanical'],
      isActive: true,
      items: [
        {
          id: 'km_teste',
          label: 'Quilometragem do Teste',
          type: 'number',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'ruidos',
          label: 'Ruídos Identificados',
          type: 'checklist',
          options: ['Motor', 'Suspensão', 'Freios', 'Câmbio', 'Direção', 'Nenhum'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'vibracao',
          label: 'Vibração no Volante',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'freio_ok',
          label: 'Frenagem Normal',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'direcao_ok',
          label: 'Direção Alinhada',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'aprovado',
          label: 'Veículo Aprovado no Teste',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'entrega_veiculo',
      title: 'Entrega do Veículo',
      description: 'Confirme limpeza, itens devolvidos e serviços com o cliente.',
      subspecialties: ['mechanical', 'carwash', 'painting', 'bodywork'],
      isActive: true,
      items: [
        {
          id: 'veiculo_limpo',
          label: 'Veículo Lavado/Limpo',
          type: 'boolean',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'servicos_conferidos',
          label: 'Serviços Conferidos com Cliente',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'itens_devolvidos',
          label: 'Itens Devolvidos',
          type: 'checklist',
          options: ['Documentos', 'Chaves', 'Estepe', 'Triângulo', 'Macaco'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_painel',
          label: 'Foto do Painel (km final)',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'termo_autorizacao_automotive',
      title: 'Autorização do Cliente (Veículo)',
      description: 'Registra consentimento para testes, movimentação e fotos.',
      subspecialties: ['mechanical', 'carwash', 'painting', 'bodywork'],
      isActive: true,
      items: [
        {
          id: 'autorizacao_movimentacao',
          label: 'Autorizo a movimentação do veículo na oficina',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'autorizacao_teste_rodagem',
          label: 'Autorizo teste de rodagem quando necessário',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'ciencia_registro_fotos',
          label: 'Ciente do registro de fotos para evidências do serviço',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'itens_sensiveis',
          label: 'Itens sensíveis/valor no veículo',
          type: 'checklist',
          options: ['Dashcam', 'Som/Multimídia', 'Ferramentas', 'Objetos de valor', 'Sem itens'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'observacoes_cliente',
          label: 'Observações do Cliente',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'checklist_seguranca_final_auto',
      title: 'Segurança Final do Veículo',
      description: 'Revisão final de itens críticos antes da liberação.',
      subspecialties: ['mechanical', 'painting', 'bodywork'],
      isActive: true,
      items: [
        {
          id: 'torque_rodas',
          label: 'Torque/Reaperto das rodas conferido (se aplicável)',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'nivel_oleo',
          label: 'Nível de óleo verificado',
          type: 'select',
          options: ['OK', 'Baixo', 'Não aplicável'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'nivel_fluido_freio',
          label: 'Nível do fluido de freio verificado',
          type: 'select',
          options: ['OK', 'Baixo', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'verificacao_vazamentos',
          label: 'Verificação de vazamentos',
          type: 'select',
          options: ['Sem vazamentos', 'Vazamento identificado'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'luzes_externas',
          label: 'Luzes externas testadas',
          type: 'checklist',
          options: ['Farol baixo', 'Farol alto', 'Lanterna', 'Freio', 'Ré', 'Setas', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_compartimento_motor',
          label: 'Foto do compartimento do motor (pós-serviço)',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // HVAC - Ar Condicionado / Refrigeração
  // ═══════════════════════════════════════════════════════════
  hvac: [
    {
      id: 'laudo_instalacao',
      title: 'Registro da Instalação',
      description: 'Fotos e medições básicas para comprovar a instalação.',
      subspecialties: ['residential', 'commercial', 'automotive_ac'],
      isActive: true,
      items: [
        {
          id: 'foto_evaporadora',
          label: 'Foto da Evaporadora (Interna)',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'foto_condensadora',
          label: 'Foto da Condensadora (Externa)',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'teste_dreno',
          label: 'Teste de Dreno Realizado?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'vacuo_sistema',
          label: 'Vácuo no Sistema Realizado?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'pressao_gas',
          label: 'Pressão do Gás (PSI)',
          type: 'number',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'temp_saida',
          label: 'Temperatura de Saída (°C)',
          type: 'number',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'manutencao_preventiva',
      title: 'Manutenção Preventiva',
      description: 'Checklist de limpeza e verificação periódica do equipamento.',
      subspecialties: ['residential', 'commercial', 'automotive_ac'],
      isActive: true,
      items: [
        {
          id: 'filtros_limpos',
          label: 'Filtros Limpos/Trocados',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'evaporadora_limpa',
          label: 'Evaporadora Higienizada',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'condensadora_limpa',
          label: 'Condensadora Limpa',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'dreno_desobstruido',
          label: 'Dreno Desobstruído',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'bandeja_limpa',
          label: 'Bandeja de Drenagem Limpa',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'verificacao_eletrica',
          label: 'Verificação Elétrica',
          type: 'checklist',
          options: ['Disjuntor OK', 'Fiação OK', 'Conexões OK', 'Aterramento OK'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_funcionamento',
          label: 'Teste de Funcionamento OK',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'diagnostico_tecnico',
      title: 'Diagnóstico do Equipamento',
      description: 'Registre sintomas e testes para identificar o problema.',
      subspecialties: ['residential', 'commercial', 'automotive_ac'],
      isActive: true,
      items: [
        {
          id: 'sintoma_relatado',
          label: 'Sintoma Relatado pelo Cliente',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'equipamento_liga',
          label: 'Equipamento Liga?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'compressor_funciona',
          label: 'Compressor Funciona?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'nivel_gas',
          label: 'Nível de Gás',
          type: 'select',
          options: ['OK', 'Baixo', 'Zerado', 'Não verificado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'vazamento',
          label: 'Vazamento Detectado?',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'capacitor',
          label: 'Estado do Capacitor',
          type: 'select',
          options: ['OK', 'Fraco', 'Queimado', 'Não verificado'],
          required: false,
          allowPhotos: true,
        },
        {
          id: 'diagnostico_final',
          label: 'Diagnóstico Final',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'recarga_gas',
      title: 'Recarga de Gás',
      description: 'Anote tipo e quantidade de gás e medições antes/depois.',
      subspecialties: ['residential', 'commercial', 'automotive_ac'],
      isActive: true,
      items: [
        {
          id: 'tipo_gas',
          label: 'Tipo de Gás',
          type: 'select',
          options: ['R-22', 'R-410A', 'R-32', 'R-134a', 'R-404A', 'R-407C'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'quantidade_gas',
          label: 'Quantidade Utilizada (g)',
          type: 'number',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'pressao_antes',
          label: 'Pressão Antes (PSI)',
          type: 'number',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'pressao_depois',
          label: 'Pressão Depois (PSI)',
          type: 'number',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'temp_saida_final',
          label: 'Temperatura de Saída Final (°C)',
          type: 'number',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_vazamento',
          label: 'Teste de Vazamento Realizado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'checklist_seguranca_hvac',
      title: 'Segurança do Técnico (NR10/NR35)',
      description: 'Confere EPIs e segurança do local antes de iniciar.',
      subspecialties: ['residential', 'commercial'],
      isActive: true,
      items: [
        {
          id: 'energia_bloqueada',
          label: 'Energia desligada e bloqueada/identificada',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'epi_utilizado',
          label: 'EPI utilizado',
          type: 'checklist',
          options: ['Luvas', 'Óculos', 'Botina', 'Máscara', 'Cinto/Trava-quedas', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'area_sinalizada',
          label: 'Área sinalizada e protegida',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'escada_ancorada',
          label: 'Escada/andaime seguro (quando aplicável)',
          type: 'select',
          options: ['OK', 'Não aplicável', 'Não conforme'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'foto_area',
          label: 'Foto da área de trabalho',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'comissionamento_pos_servico_hvac',
      title: 'Comissionamento Pós-Serviço',
      description: 'Medições finais para validar desempenho e reduzir retorno.',
      subspecialties: ['residential', 'commercial', 'automotive_ac'],
      isActive: true,
      items: [
        {
          id: 'tensao',
          label: 'Tensão (V)',
          type: 'number',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'corrente',
          label: 'Corrente (A)',
          type: 'number',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'delta_t',
          label: 'Diferença de temperatura (ΔT °C)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'dreno_ok',
          label: 'Dreno testado e ok',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'isolamento_tubulacao',
          label: 'Isolamento da tubulação',
          type: 'select',
          options: ['OK', 'Parcial', 'Ausente'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'teste_vazamento',
          label: 'Teste de vazamento realizado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_instalacao_final',
          label: 'Foto da instalação final',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // SMARTPHONES - Assistência Técnica - Celulares
  // ═══════════════════════════════════════════════════════════
  smartphones: [
    {
      id: 'checklist_entrada_cel',
      title: 'Entrada do Celular',
      description: 'Registra o estado inicial e os acessórios recebidos.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'fotos_aparelho',
          label: 'Fotos do Aparelho (Frente/Verso)',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'tela_quebrada',
          label: 'Tela Quebrada/Trincada?',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'liga',
          label: 'Aparelho Liga?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'touch_funciona',
          label: 'Touch Funciona?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'biometria',
          label: 'Touch ID / Face ID Funciona?',
          type: 'select',
          options: ['Funciona', 'Não funciona', 'Não possui', 'Não testado'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'avarias_visiveis',
          label: 'Avarias Visíveis',
          type: 'checklist',
          options: ['Riscos na Tela', 'Amassados', 'Botões danificados', 'Câmera riscada', 'Nenhuma'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'senha_desbloqueio',
          label: 'Senha de Desbloqueio',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'acessorios',
          label: 'Acessórios Deixados',
          type: 'checklist',
          options: ['Carregador', 'Cabo', 'Capinha', 'Película', 'Caixa', 'Nenhum'],
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'diagnostico_cel',
      title: 'Diagnóstico Completo do Celular',
      description: 'Testa funções principais para identificar falhas.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'teste_display',
          label: 'Display',
          type: 'select',
          options: ['OK', 'Manchas', 'Linhas', 'Não funciona'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'teste_touch',
          label: 'Touch',
          type: 'select',
          options: ['OK', 'Pontos mortos', 'Ghost touch', 'Não funciona'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_bateria',
          label: 'Saúde da Bateria (%)',
          type: 'number',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'teste_camera_traseira',
          label: 'Câmera Traseira',
          type: 'select',
          options: ['OK', 'Desfocada', 'Não funciona'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_camera_frontal',
          label: 'Câmera Frontal',
          type: 'select',
          options: ['OK', 'Desfocada', 'Não funciona'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_audio',
          label: 'Alto-falante / Microfone',
          type: 'select',
          options: ['OK', 'Baixo', 'Chiando', 'Não funciona'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_wifi',
          label: 'Wi-Fi',
          type: 'select',
          options: ['OK', 'Sinal fraco', 'Não conecta'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_bluetooth',
          label: 'Bluetooth',
          type: 'select',
          options: ['OK', 'Não encontra', 'Não pareia'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'teste_carregamento',
          label: 'Carregamento',
          type: 'select',
          options: ['OK', 'Lento', 'Só wireless', 'Não carrega'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_botoes',
          label: 'Botões Físicos',
          type: 'checklist',
          options: ['Power OK', 'Volume OK', 'Home OK', 'Mute OK'],
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'troca_tela',
      title: 'Troca de Tela',
      description: 'Confere peça instalada e testes após a troca do display.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'tipo_tela',
          label: 'Tipo de Tela Instalada',
          type: 'select',
          options: ['Original', 'Compatível Premium', 'Compatível Standard'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'cola_aplicada',
          label: 'Cola/Vedação Aplicada',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_touch_pos',
          label: 'Teste de Touch Pós-Troca',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_true_tone',
          label: 'True Tone Funcionando (iOS)',
          type: 'select',
          options: ['Sim', 'Não', 'Não aplicável'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'teste_face_id',
          label: 'Face ID Funcionando (iOS)',
          type: 'select',
          options: ['Sim', 'Não', 'Não aplicável'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'foto_final',
          label: 'Foto do Aparelho Finalizado',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'troca_bateria',
      title: 'Troca de Bateria',
      description: 'Registra a bateria instalada e testes de funcionamento.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'saude_antes',
          label: 'Saúde da Bateria Antes (%)',
          type: 'number',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'tipo_bateria',
          label: 'Tipo de Bateria',
          type: 'select',
          options: ['Original', 'Compatível Premium', 'Compatível Standard'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'vedacao_aplicada',
          label: 'Vedação/Adesivo Aplicado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'calibracao',
          label: 'Ciclo de Calibração Orientado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'saude_depois',
          label: 'Saúde da Bateria Nova (%)',
          type: 'number',
          required: true,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'termo_autorizacao_smartphones',
      title: 'Autorização e Privacidade (Celular)',
      description: 'Consentimento para acesso, backup e registro do reparo.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'backup_cliente',
          label: 'Backup do cliente',
          type: 'select',
          options: ['Já possui backup', 'Solicitado backup', 'Cliente recusou'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'senha_fornecida',
          label: 'Senha/PIN fornecido (se necessário)',
          type: 'select',
          options: ['Sim', 'Não', 'Não necessário'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'ciencia_perda_dados',
          label: 'Ciente do risco de perda de dados durante o reparo',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'pecas',
          label: 'Preferência de peças',
          type: 'select',
          options: ['Original', 'Compatível Premium', 'Compatível Standard', 'A definir'],
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'teste_pos_reparo_cel',
      title: 'Teste Final do Celular',
      description: 'Checklist final para garantir que tudo funciona.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'liga',
          label: 'Aparelho liga',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'carregamento',
          label: 'Carregamento',
          type: 'select',
          options: ['OK', 'Lento', 'Não carrega', 'Não testado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'rede_wifi',
          label: 'Wi-Fi',
          type: 'select',
          options: ['OK', 'Não conecta', 'Não testado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'cameras',
          label: 'Câmeras/Flash',
          type: 'checklist',
          options: ['Traseira OK', 'Frontal OK', 'Flash OK', 'Não testado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'audio',
          label: 'Áudio',
          type: 'checklist',
          options: ['Alto-falante OK', 'Microfone OK', 'Fone/Bluetooth OK', 'Não testado'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'sensores',
          label: 'Sensores',
          type: 'checklist',
          options: ['Proximidade', 'Giroscópio', 'Bússola', 'GPS', 'Não testado', 'N/A'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'foto_final',
          label: 'Foto do aparelho finalizado',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // COMPUTADORES - Informática
  // ═══════════════════════════════════════════════════════════
  computers: [
    {
      id: 'checklist_entrada_pc',
      title: 'Entrada do Computador',
      description: 'Registra o estado inicial e os acessórios recebidos.',
      subspecialties: ['desktop', 'notebook', 'servers'],
      isActive: true,
      items: [
        {
          id: 'fotos_equipamento',
          label: 'Fotos do Equipamento',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'tipo_equipamento',
          label: 'Tipo',
          type: 'select',
          options: ['Desktop', 'Notebook', 'All-in-One', 'Monitor', 'Outro'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'liga',
          label: 'Equipamento Liga?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'tela_ok',
          label: 'Tela Funciona?',
          type: 'select',
          options: ['OK', 'Manchas', 'Linhas', 'Não funciona', 'N/A'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'avarias',
          label: 'Avarias Visíveis',
          type: 'checklist',
          options: ['Carcaça quebrada', 'Teclado danificado', 'Dobradiças', 'Portas danificadas', 'Nenhuma'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'acessorios',
          label: 'Acessórios Deixados',
          type: 'checklist',
          options: ['Carregador', 'Mouse', 'Teclado', 'Cabos', 'HD externo', 'Nenhum'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'senha',
          label: 'Senha de Acesso',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'diagnostico_hardware',
      title: 'Diagnóstico de Hardware',
      description: 'Testa componentes para identificar o defeito.',
      subspecialties: ['desktop', 'notebook', 'servers'],
      isActive: true,
      items: [
        {
          id: 'teste_memoria',
          label: 'Memória RAM',
          type: 'select',
          options: ['OK', 'Erro detectado', 'Não reconhecida'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_hd',
          label: 'HD/SSD',
          type: 'select',
          options: ['OK', 'Setores ruins', 'Lento', 'Não detectado'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'saude_hd',
          label: 'Saúde do HD/SSD (%)',
          type: 'number',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'teste_fonte',
          label: 'Fonte de Alimentação',
          type: 'select',
          options: ['OK', 'Instável', 'Não funciona'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_placa_mae',
          label: 'Placa Mãe',
          type: 'select',
          options: ['OK', 'Capacitor estufado', 'Não liga', 'POST com erro'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'teste_cooler',
          label: 'Coolers/Ventilação',
          type: 'select',
          options: ['OK', 'Ruidoso', 'Parado', 'Não possui'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'temperatura',
          label: 'Temperatura CPU (°C)',
          type: 'number',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'diagnostico',
          label: 'Diagnóstico Final',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'formatacao',
      title: 'Formatação e Instalação do Sistema',
      description: 'Registra backup, instalação e configurações básicas.',
      subspecialties: ['desktop', 'notebook', 'servers'],
      isActive: true,
      items: [
        {
          id: 'backup_feito',
          label: 'Backup dos Dados Realizado',
          type: 'select',
          options: ['Sim', 'Não solicitado', 'Cliente recusou'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'sistema_instalado',
          label: 'Sistema Operacional Instalado',
          type: 'select',
          options: ['Windows 10', 'Windows 11', 'macOS', 'Linux', 'Outro'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'drivers_instalados',
          label: 'Drivers Instalados',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'atualizacoes',
          label: 'Atualizações do Sistema',
          type: 'select',
          options: ['Atualizadas', 'Parcial', 'Não atualizado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'programas_instalados',
          label: 'Programas Básicos Instalados',
          type: 'checklist',
          options: ['Navegador', 'Office', 'Antivírus', 'PDF Reader', 'Compactador'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'dados_restaurados',
          label: 'Dados Restaurados',
          type: 'select',
          options: ['Sim', 'Não tinha backup', 'Não solicitado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_geral',
          label: 'Teste Geral OK',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'limpeza_interna',
      title: 'Limpeza Interna',
      description: 'Checklist de limpeza e troca de pasta térmica.',
      subspecialties: ['desktop', 'notebook', 'servers'],
      isActive: true,
      items: [
        {
          id: 'foto_antes',
          label: 'Foto Antes da Limpeza',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'limpeza_coolers',
          label: 'Coolers Limpos',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'limpeza_dissipador',
          label: 'Dissipador Limpo',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'pasta_termica',
          label: 'Pasta Térmica Trocada',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'limpeza_geral',
          label: 'Limpeza Geral Interna',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_depois',
          label: 'Foto Após a Limpeza',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'temp_antes',
          label: 'Temperatura Antes (°C)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'temp_depois',
          label: 'Temperatura Depois (°C)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'upgrade_hardware',
      title: 'Upgrade de Hardware',
      description: 'Registra componentes trocados e testes realizados.',
      subspecialties: ['desktop', 'notebook', 'servers'],
      isActive: true,
      items: [
        {
          id: 'componente_upgrade',
          label: 'Componente Alterado',
          type: 'checklist',
          options: ['Memória RAM', 'HD/SSD', 'Processador', 'Placa de Vídeo', 'Fonte', 'Outro'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'especificacao_antiga',
          label: 'Especificação Anterior',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'especificacao_nova',
          label: 'Especificação Nova',
          type: 'text',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'teste_stress',
          label: 'Teste de Stress Realizado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'sistema_reconhece',
          label: 'Sistema Reconhece Novo Hardware',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'termo_privacidade_pc',
      title: 'Privacidade e Backup (Computador)',
      description: 'Autoriza acesso a dados e testes quando necessário.',
      subspecialties: ['desktop', 'notebook', 'servers'],
      isActive: true,
      items: [
        {
          id: 'backup',
          label: 'Backup dos dados',
          type: 'select',
          options: ['Realizado', 'Não solicitado', 'Cliente recusou', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'ciencia_privacidade',
          label: 'Ciente que arquivos podem ser acessados durante diagnóstico/reparo',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'autorizacao_testes',
          label: 'Autorizo testes de estresse/benchmarks quando necessário',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'senha_acesso',
          label: 'Senha de acesso (se aplicável)',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'checklist_qualidade_pos_servico_pc',
      title: 'Qualidade na Entrega (Computador)',
      description: 'Verificações finais antes de entregar o equipamento.',
      subspecialties: ['desktop', 'notebook', 'servers'],
      isActive: true,
      items: [
        {
          id: 'atualizacoes',
          label: 'Sistema atualizado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'antivirus',
          label: 'Antivírus',
          type: 'select',
          options: ['Instalado', 'Já tinha', 'Não solicitado', 'N/A'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'senha_usuario',
          label: 'Senha do usuário',
          type: 'select',
          options: ['Atualizada', 'Mantida', 'N/A'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_perifericos',
          label: 'Teste de periféricos',
          type: 'checklist',
          options: ['Áudio OK', 'Microfone OK', 'Webcam OK', 'USB OK', 'Wi-Fi OK', 'N/A'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'foto_area_trabalho',
          label: 'Foto do equipamento finalizado',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // ELETRODOMÉSTICOS
  // ═══════════════════════════════════════════════════════════
  appliances: [
    {
      id: 'checklist_entrada_eletro',
      title: 'Entrada do Eletrodoméstico',
      description: 'Registra o estado inicial e o defeito relatado.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'fotos_equipamento',
          label: 'Fotos do Equipamento',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'tipo_equipamento',
          label: 'Tipo de Equipamento',
          type: 'select',
          options: ['Geladeira', 'Máquina de Lavar', 'Micro-ondas', 'Fogão', 'Lava-louças', 'Outro'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'liga',
          label: 'Equipamento Liga?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'avarias_visiveis',
          label: 'Avarias Visíveis',
          type: 'checklist',
          options: ['Amassados', 'Ferrugem', 'Botões quebrados', 'Vidro trincado', 'Nenhuma'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'defeito_relatado',
          label: 'Defeito Relatado',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'diagnostico_geladeira',
      title: 'Diagnóstico de Geladeira/Freezer',
      description: 'Testa refrigeração e componentes principais.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'compressor_funciona',
          label: 'Compressor Funciona?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'motor_ventilador',
          label: 'Motor Ventilador',
          type: 'select',
          options: ['OK', 'Ruidoso', 'Parado', 'Não possui'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'gas_ok',
          label: 'Gás Refrigerante OK',
          type: 'select',
          options: ['OK', 'Baixo', 'Zerado', 'Não verificado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'termostato',
          label: 'Termostato',
          type: 'select',
          options: ['OK', 'Defeituoso', 'Não testado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'borracha_porta',
          label: 'Borracha da Porta',
          type: 'select',
          options: ['OK', 'Ressecada', 'Rasgada', 'Solta'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'degelo',
          label: 'Sistema de Degelo',
          type: 'select',
          options: ['OK', 'Resistência queimada', 'Timer defeituoso', 'N/A'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'temperatura_interna',
          label: 'Temperatura Interna (°C)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'diagnostico_maquina_lavar',
      title: 'Diagnóstico de Máquina de Lavar',
      description: 'Testa enchimento, drenagem e componentes.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'enche_agua',
          label: 'Enche Água Normalmente?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'drena_agua',
          label: 'Drena Água Normalmente?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'centrifuga',
          label: 'Centrifuga Normalmente?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'motor',
          label: 'Motor',
          type: 'select',
          options: ['OK', 'Ruidoso', 'Travado', 'Queimado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'bomba_drenagem',
          label: 'Bomba de Drenagem',
          type: 'select',
          options: ['OK', 'Entupida', 'Queimada'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'placa_eletronica',
          label: 'Placa Eletrônica',
          type: 'select',
          options: ['OK', 'Com defeito', 'Não testada'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'rolamentos',
          label: 'Rolamentos/Retentores',
          type: 'select',
          options: ['OK', 'Ruidoso', 'Vazando', 'Não verificado'],
          required: false,
          allowPhotos: false,
        },
        {
          id: 'vazamento',
          label: 'Vazamento Detectado?',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'diagnostico_microondas',
      title: 'Diagnóstico de Micro-ondas',
      description: 'Testa painel, aquecimento e segurança.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'painel_funciona',
          label: 'Painel Funciona?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'prato_gira',
          label: 'Prato Giratório Funciona?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'aquece',
          label: 'Aquece Normalmente?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'magnetron',
          label: 'Magnetron',
          type: 'select',
          options: ['OK', 'Fraco', 'Queimado', 'Não testado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'capacitor',
          label: 'Capacitor',
          type: 'select',
          options: ['OK', 'Descarregado', 'Queimado', 'Não testado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'trava_porta',
          label: 'Trava da Porta',
          type: 'select',
          options: ['OK', 'Defeituosa', 'Quebrada'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'faz_barulho',
          label: 'Ruídos Anormais?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'entrega_eletro',
      title: 'Entrega do Eletrodoméstico',
      description: 'Confere serviço executado e orientações ao cliente.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'servico_executado',
          label: 'Serviço Executado',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_final',
          label: 'Teste Final Realizado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'equipamento_limpo',
          label: 'Equipamento Limpo',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'pecas_trocadas',
          label: 'Peças Trocadas',
          type: 'text',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'orientacoes',
          label: 'Orientações ao Cliente',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'garantia',
          label: 'Garantia do Serviço',
          type: 'select',
          options: ['30 dias', '60 dias', '90 dias', 'Sem garantia'],
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'checklist_seguranca_appliances',
      title: 'Segurança do Equipamento',
      description: 'Confere riscos elétricos/gás antes e após o serviço.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'desligado_rede',
          label: 'Equipamento desconectado/desenergizado antes do serviço',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'aterramento',
          label: 'Aterramento',
          type: 'select',
          options: ['OK', 'Ausente', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_fuga',
          label: 'Teste de fuga/isolação',
          type: 'select',
          options: ['OK', 'Falha', 'Não aplicável'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'vazamento_gas',
          label: 'Teste de vazamento de gás (quando aplicável)',
          type: 'select',
          options: ['Sem vazamento', 'Vazamento identificado', 'Não aplicável'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'foto_instalacao',
          label: 'Foto da instalação/local',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'teste_pos_reparo_appliances',
      title: 'Teste Final do Equipamento',
      description: 'Valida funcionamento após o reparo.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'ciclo_teste',
          label: 'Ciclo de teste',
          type: 'select',
          options: ['Realizado (completo)', 'Parcial', 'Não realizado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'ruidos',
          label: 'Ruídos',
          type: 'select',
          options: ['Normal', 'Anormal', 'Não testado'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'vazamentos',
          label: 'Vazamentos',
          type: 'select',
          options: ['Sem vazamentos', 'Vazamento identificado', 'Não aplicável'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'aprovado',
          label: 'Aprovado para entrega',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_final',
          label: 'Foto final',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // ELÉTRICA (Residencial/Predial)
  // ═══════════════════════════════════════════════════════════
  electrical: [
    {
      id: 'checklist_seguranca_eletrica',
      title: 'Segurança do Serviço Elétrico (NR10)',
      description: 'Checklist antes de iniciar para evitar acidentes.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'desenergizado',
          label: 'Circuito desenergizado e bloqueado/identificado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_ausencia_tensao',
          label: 'Teste de ausência de tensão realizado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'epi',
          label: 'EPI utilizado',
          type: 'checklist',
          options: ['Luvas isolantes', 'Óculos', 'Botina', 'Capacete', 'Máscara', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'area_sinalizada',
          label: 'Área sinalizada/protegida',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_quadro',
          label: 'Foto do quadro/instalação antes',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'laudo_servico_eletrico',
      title: 'Registro do Serviço Elétrico',
      description: 'Resumo do serviço e medições realizadas.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'servico_executado',
          label: 'Serviço executado',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'tensao_medida',
          label: 'Tensão medida (V)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'corrente_medida',
          label: 'Corrente medida (A)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'dr_testado',
          label: 'DR testado (quando aplicável)',
          type: 'select',
          options: ['OK', 'Falha', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'aterramento',
          label: 'Aterramento',
          type: 'select',
          options: ['OK', 'Ausente', 'Não aplicável'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'foto_depois',
          label: 'Foto do quadro/instalação após',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'checklist_qualidade_eletrica',
      title: 'Qualidade na Entrega (Elétrica)',
      description: 'Verificações finais de segurança e organização.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'aperto_conexoes',
          label: 'Aperto/conferência de conexões (se aplicável)',
          type: 'select',
          options: ['OK', 'Não aplicável', 'Não realizado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'identificacao_circuitos',
          label: 'Circuitos identificados/etiquetados',
          type: 'select',
          options: ['OK', 'Parcial', 'Não aplicável'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'teste_funcional',
          label: 'Teste funcional (pontos atendidos)',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'limpeza',
          label: 'Local limpo e organizado',
          type: 'boolean',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // HIDRÁULICA (Encanador)
  // ═══════════════════════════════════════════════════════════
  plumbing: [
    {
      id: 'checklist_seguranca_hidraulica',
      title: 'Segurança do Serviço Hidráulico',
      description: 'Prepara o local para evitar danos e acidentes.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'registro_fechado',
          label: 'Registro fechado/isolamento da linha',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'epi',
          label: 'EPI utilizado',
          type: 'checklist',
          options: ['Luvas', 'Óculos', 'Máscara', 'Botina', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'protecao_area',
          label: 'Área protegida (piso/móveis) e pano/balde preparados',
          type: 'boolean',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'foto_local',
          label: 'Foto do local antes',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'teste_estanqueidade',
      title: 'Teste de Estanqueidade',
      description: 'Confirma ausência de vazamentos após o serviço.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'metodo',
          label: 'Método do teste',
          type: 'select',
          options: ['Pressurização', 'Observação', 'Corante', 'Outro'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'tempo_min',
          label: 'Tempo de observação (min)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'resultado',
          label: 'Resultado',
          type: 'select',
          options: ['Sem vazamentos', 'Vazamento identificado', 'Não concluído'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'foto_teste',
          label: 'Foto/evidência do teste',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'entrega_hidraulica',
      title: 'Entrega do Serviço Hidráulico',
      description: 'Checklist final e orientações ao cliente.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'servico_executado',
          label: 'Serviço executado',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'teste_funcional',
          label: 'Teste funcional realizado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'orientacoes',
          label: 'Orientações ao cliente',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'foto_final',
          label: 'Foto final',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // SEGURANÇA ELETRÔNICA (CFTV/Alarmes)
  // ═══════════════════════════════════════════════════════════
  security: [
    {
      id: 'vistoria_pre_instalacao_seguranca',
      title: 'Vistoria Pré-Instalação',
      description: 'Avalia local, energia e pontos de instalação.',
      subspecialties: ['cctv', 'alarms', 'access', 'fence'],
      isActive: true,
      items: [
        {
          id: 'tipo_sistema',
          label: 'Tipo de sistema',
          type: 'select',
          options: ['CFTV', 'Alarme', 'Controle de acesso', 'Interfonia', 'Outro'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'internet_disponivel',
          label: 'Internet disponível no local',
          type: 'select',
          options: ['Sim', 'Não', 'Parcial'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'energia_local',
          label: 'Pontos de energia disponíveis',
          type: 'select',
          options: ['OK', 'Insuficiente', 'Não avaliado'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'pontos_instalacao',
          label: 'Pontos de instalação (resumo)',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'foto_local',
          label: 'Fotos do local/pontos',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'comissionamento_seguranca',
      title: 'Comissionamento do Sistema',
      description: 'Testes finais e acesso remoto configurado.',
      subspecialties: ['cctv', 'alarms', 'access', 'fence'],
      isActive: true,
      items: [
        {
          id: 'gravacao_ok',
          label: 'Gravação/armazenamento funcionando (CFTV)',
          type: 'select',
          options: ['OK', 'Falha', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'acesso_remoto',
          label: 'Acesso remoto configurado',
          type: 'select',
          options: ['OK', 'Não solicitado', 'Falha'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'senhas_alteradas',
          label: 'Senhas padrão alteradas',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'testes',
          label: 'Testes realizados',
          type: 'checklist',
          options: ['Visualização ao vivo', 'Playback', 'Notificações', 'Sirene/Sensor', 'Zona/Partição', 'N/A'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_app',
          label: 'Foto do app/configuração (evidência)',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'termo_privacidade_seguranca',
      title: 'Autorização e Privacidade (Segurança)',
      description: 'Registra credenciais, acesso remoto e responsabilidades.',
      subspecialties: ['cctv', 'alarms', 'access', 'fence'],
      isActive: true,
      items: [
        {
          id: 'responsavel_cliente',
          label: 'Responsável do cliente (nome)',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'ciencia_senhas',
          label: 'Ciente que senhas devem ser guardadas pelo cliente',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'ciencia_gravacao',
          label: 'Ciente sobre uso/gravação e obrigações legais',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // ENERGIA SOLAR
  // ═══════════════════════════════════════════════════════════
  solar: [
    {
      id: 'checklist_seguranca_solar',
      title: 'Segurança do Técnico (NR10/NR35)',
      description: 'Checklist de segurança em altura e elétrica.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'epi',
          label: 'EPI utilizado',
          type: 'checklist',
          options: ['Cinto/Trava-quedas', 'Capacete', 'Luvas', 'Óculos', 'Botina', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'linha_vida',
          label: 'Linha de vida/ancoragem verificada (quando aplicável)',
          type: 'select',
          options: ['OK', 'Não aplicável', 'Não conforme'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'desligamento',
          label: 'Desligamento seguro (CC/CA) realizado quando aplicável',
          type: 'select',
          options: ['OK', 'Não aplicável', 'Não realizado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_area',
          label: 'Foto da área de trabalho',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'comissionamento_solar',
      title: 'Comissionamento do Sistema Solar',
      description: 'Medições finais e validação do monitoramento.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'kwp',
          label: 'Potência do sistema (kWp)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'tensao_cc',
          label: 'Tensão CC (V) (string principal)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'corrente_cc',
          label: 'Corrente CC (A) (string principal)',
          type: 'number',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'monitoramento',
          label: 'Monitoramento/app configurado',
          type: 'select',
          options: ['OK', 'Não solicitado', 'Pendência'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_inversor',
          label: 'Foto do inversor/quadros',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'entrega_solar',
      title: 'Entrega e Orientações (Solar)',
      description: 'Confirma orientações e acesso do cliente.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'orientacoes',
          label: 'Orientações repassadas (monitoramento, desligamento, manutenção)',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'acesso_cliente',
          label: 'Acesso do cliente ao portal/app',
          type: 'select',
          options: ['Ativo', 'Pendente', 'Não solicitado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'garantia',
          label: 'Garantia/termos entregues',
          type: 'select',
          options: ['Entregue', 'Pendente', 'N/A'],
          required: true,
          allowPhotos: false,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // IMPRESSORAS / COPIADORAS
  // ═══════════════════════════════════════════════════════════
  printers: [
    {
      id: 'checklist_entrada_printers',
      title: 'Entrada da Impressora',
      description: 'Registra estado, contador e defeito relatado.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'fotos',
          label: 'Fotos do equipamento',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'tipo',
          label: 'Tipo',
          type: 'select',
          options: ['Laser', 'Jato de tinta', 'Térmica', 'Matricial', 'Outra'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'contador_paginas',
          label: 'Contador de páginas',
          type: 'number',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'defeito',
          label: 'Defeito relatado',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'acessorios',
          label: 'Acessórios deixados',
          type: 'checklist',
          options: ['Fonte', 'Cabo USB', 'Cabo de força', 'Bandeja', 'Nenhum'],
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'manutencao_preventiva_printers',
      title: 'Manutenção Preventiva',
      description: 'Limpeza e ajustes para reduzir retorno.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'limpeza',
          label: 'Limpeza interna/externa',
          type: 'select',
          options: ['Realizada', 'Parcial', 'Não realizada'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'roletes',
          label: 'Roletes/Separadores',
          type: 'select',
          options: ['OK', 'Desgastado', 'Substituído', 'Não aplicável'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'firmware',
          label: 'Firmware/driver atualizado (quando aplicável)',
          type: 'select',
          options: ['Atualizado', 'Já estava', 'Não aplicável', 'Não realizado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'calibracao',
          label: 'Calibração/Alinhamento',
          type: 'select',
          options: ['OK', 'Não aplicável', 'Não realizado'],
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'teste_pos_servico_printers',
      title: 'Teste Final da Impressora',
      description: 'Testes finais para garantir a entrega.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'impressao_teste',
          label: 'Impressão teste',
          type: 'select',
          options: ['OK', 'Falha', 'Não testado'],
          required: true,
          allowPhotos: true,
        },
        {
          id: 'scanner',
          label: 'Scanner/Cópia (se aplicável)',
          type: 'select',
          options: ['OK', 'Falha', 'Não aplicável', 'Não testado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'rede',
          label: 'Rede (Wi-Fi/Ethernet)',
          type: 'select',
          options: ['OK', 'Falha', 'Não aplicável', 'Não testado'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_pagina_teste',
          label: 'Foto da página teste (evidência)',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'aprovado',
          label: 'Aprovado para entrega',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════
  // OUTRO (Genérico)
  // ═══════════════════════════════════════════════════════════
  other: [
    {
      id: 'checklist_entrada_generico',
      title: 'Entrada do Item',
      description: 'Registra condição inicial e defeito relatado.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'fotos_item',
          label: 'Fotos do Item',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'descricao_item',
          label: 'Descrição do Item',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'funciona',
          label: 'Item Funciona?',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'avarias',
          label: 'Avarias Visíveis',
          type: 'text',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'defeito_relatado',
          label: 'Defeito Relatado',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'acessorios',
          label: 'Acessórios Deixados',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'diagnostico_generico',
      title: 'Diagnóstico do Item',
      description: 'Análise técnica para identificar o problema.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'analise',
          label: 'Análise Realizada',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'problema_encontrado',
          label: 'Problema Identificado',
          type: 'text',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'solucao_proposta',
          label: 'Solução Proposta',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'fotos_diagnostico',
          label: 'Fotos do Diagnóstico',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'laudo_servico',
      title: 'Registro do Serviço',
      description: 'Resumo do que foi feito e evidências.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'servico_realizado',
          label: 'Serviço Realizado',
          type: 'text',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'pecas_utilizadas',
          label: 'Peças/Materiais Utilizados',
          type: 'text',
          required: false,
          allowPhotos: true,
        },
        {
          id: 'teste_final',
          label: 'Teste Final OK',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'fotos_servico',
          label: 'Fotos do Serviço',
          type: 'photo_only',
          required: true,
          allowPhotos: true,
        },
        {
          id: 'observacoes',
          label: 'Observações',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'entrega_generico',
      title: 'Entrega ao Cliente',
      description: 'Confirma entrega, funcionamento e garantia.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'item_conferido',
          label: 'Item Conferido com Cliente',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'funcionamento_ok',
          label: 'Funcionamento Demonstrado',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'orientacoes',
          label: 'Orientações Passadas',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'garantia',
          label: 'Prazo de Garantia',
          type: 'select',
          options: ['30 dias', '60 dias', '90 dias', 'Sem garantia'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'foto_entrega',
          label: 'Foto na Entrega',
          type: 'photo_only',
          required: false,
          allowPhotos: true,
        },
      ],
    },
    {
      id: 'termo_autorizacao_generico',
      title: 'Autorização e Privacidade',
      description: 'Consentimento para execução e registro do serviço.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'autorizacao_execucao',
          label: 'Autorizo a execução do serviço conforme orçamento',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'ciencia_riscos',
          label: 'Ciente de riscos inerentes e limites do serviço',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
        {
          id: 'ciencia_privacidade',
          label: 'Ciente do registro de fotos e uso para evidências do serviço',
          type: 'boolean',
          required: true,
          allowPhotos: false,
        },
      ],
    },
    {
      id: 'pesquisa_satisfacao_nps',
      title: 'Pesquisa de Satisfação',
      description: 'Avalia a experiência do cliente após o serviço.',
      subspecialties: [],
      isActive: true,
      items: [
        {
          id: 'nota',
          label: 'De 0 a 10, o quanto você recomendaria nosso serviço?',
          type: 'select',
          options: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
          required: true,
          allowPhotos: false,
        },
        {
          id: 'motivo',
          label: 'O que motivou sua nota?',
          type: 'text',
          required: false,
          allowPhotos: false,
        },
        {
          id: 'autorizacao_depoimento',
          label: 'Autoriza usar seu depoimento (sem dados sensíveis)?',
          type: 'boolean',
          required: false,
          allowPhotos: false,
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════
// FUNÇÃO DE SEED
// ═══════════════════════════════════════════════════════════════════════════

async function seedForms() {
  console.log('════════════════════════════════════════════════════════════');
  console.log('  POPULANDO FORMULÁRIOS GLOBAIS (SEGMENTOS)');
  console.log('  Path: /segments/{segmentId}/forms/{formId}');
  console.log('════════════════════════════════════════════════════════════\n');

  try {
    let created = 0;
    let updated = 0;
    let skipped = 0;

    for (const [segmentId, forms] of Object.entries(GLOBAL_FORMS)) {
      console.log(`\n📂 Processando segmento: ${segmentId}`);
      console.log(`   Formulários a processar: ${forms.length}`);

      const segmentRef = db.collection('segments').doc(segmentId);
      // Garante que o segmento existe (apenas check rápido)
      const segDoc = await segmentRef.get();
      if (!segDoc.exists) {
        console.log(`   ⚠️  Segmento ${segmentId} não encontrado. Pulando...`);
        skipped += forms.length;
        continue;
      }

      for (const form of forms) {
        // Apply i18n translations to the form
        const translatedForm = applyTranslations(form);
        const { id, ...data } = translatedForm;
        const normalizedData = {
          ...data,
          subspecialties: Array.isArray(data.subspecialties) ? data.subspecialties : [],
        };
        const formRef = segmentRef.collection('forms').doc(id);
        const formDoc = await formRef.get();

        if (formDoc.exists) {
          console.log(`   ↻ Atualizando: ${normalizedData.title}`);
          await formRef.set({
            ...normalizedData,
            updatedAt: admin.firestore.FieldValue.serverTimestamp(),
          }, { merge: true });
          updated++;
        } else {
          console.log(`   + Criando: ${normalizedData.title}`);
          await formRef.set({
            ...normalizedData,
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
            updatedAt: admin.firestore.FieldValue.serverTimestamp(),
          });
          created++;
        }
      }
    }

    // Resumo final
    const totalForms = Object.values(GLOBAL_FORMS).reduce((acc, forms) => acc + forms.length, 0);

    console.log('\n════════════════════════════════════════════════════════════');
    console.log('  ✅ SEED DE FORMULÁRIOS CONCLUÍDO!');
    console.log('════════════════════════════════════════════════════════════');
    console.log(`  • Total de formulários definidos: ${totalForms}`);
    console.log(`  • Criados: ${created}`);
    console.log(`  • Atualizados: ${updated}`);
    console.log(`  • Pulados (segmento inexistente): ${skipped}`);
    console.log('════════════════════════════════════════════════════════════');
    console.log('\n📋 Resumo por segmento:');
    for (const [segmentId, forms] of Object.entries(GLOBAL_FORMS)) {
      console.log(`   • ${segmentId}: ${forms.length} formulários`);
    }
    console.log('════════════════════════════════════════════════════════════\n');

    process.exit(0);
  } catch (error) {
    console.error('\n❌ Erro ao popular formulários:', error);
    process.exit(1);
  }
}

seedForms();
