default_platform(:ios)

platform :ios do
  desc "Build + upload para TestFlight (sem match)"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_PRIVATE_KEY']
    )

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )

    # Build the app
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          ENV['BUNDLE_ID'] => ENV['PROFILE_NAME']
        }
      },
      xcargs: "DEVELOPMENT_TEAM=#{ENV['DEVELOPMENT_TEAM']} " \
              "PROVISIONING_PROFILE=#{ENV['PROFILE_UUID']} " \
              "CODE_SIGN_STYLE=Manual " \
              "CODE_SIGN_IDENTITY='Apple Distribution' " \
              "CURRENT_PROJECT_VERSION=#{build_num}"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Só envia o último .ipa"
  lane :upload do
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
