# Este arquivo é para configurar o 'snapshot' nativo do Fastlane.
# Como estamos usando 'flutter drive' para gerar screenshots (devido à falta de target de teste nativo),
# este arquivo serve apenas como referência ou se você decidir configurar o target UI Tests no Xcode.

# A list of devices you want to take the screenshots from
devices([
  "iPhone 14 Pro Max",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "pt-BR",
  "en-US"
])

# The name of the scheme which lists the UI Tests
# scheme "Runner"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

# clear_previous_screenshots true
