# A list of devices you want to take the screenshots from
devices([
  "iPhone 17 Pro Max",
  "iPhone 16e"
])

languages([
  "pt-BR"
])

# The name of the scheme which contains the UI Tests
scheme("RunnerUITests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# set the status bar to 9:41 AM
override_status_bar(true)